### ISSUE TITLE
Add a way to change what category a tag is in

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#10]
Currently if you misclick and put a tag in the wrong category there seems to be no way to fix it.

But see also my vague and rambly thoughts about categories in general:

I think my biggest bit of feedback so far (not to say this is the most important issue, just the most noticeable in my limited testing so far) is that being prompted to choose one of {activity, project, person, place} feels friction-y and restrictive. 

Is the idea with those categories that you're storing metadata about the tags? Like so that TagTime knows that "alice", "bob", and "mom" are all type "people" so that it's easy to later show statistics about how much time you spend with people?

My first intuition is that the user should worry about such ontologies themselves. Like I have tags for certain people but I also have a tag for socializing. So I don't need TagTime to keep track of which of my tags are people. I know that and can put those tags in a group myself if I want to when computing statistics, or I may just care about time spent socializing, which has its own tag.

I'm not sure what my point is. Something about how the interface for answering pings should maybe only worry about the tags and the data analysis tools should worry about grouping tags into categories.

**Comment by gkrishna63** [comment]
The little pencil icon next to the text box where you type in the tags allows you to edit your tags. Rename them, recategorize them etc. 

The categories in the ping screen are for making data entry easy. They can also be used to report. Who are the people I am working when doing Design. Show me as percentage pie chart.  

There will be further categorization over and above these for reporting. A complete tree (graph?) of categories that can contain the data entry categories as well. 

For reporting we are designing a clickable interface. Suppose you can see how time you spent on activity tag socializing the last 6 months. If you click that you will be able to see break up of where as well as who with. (this is without any special categorization)

You could further create a category called "formal socialization" and group one set of location tags and "informal socialization" and group another set of locations tags

You can create a categories called Business Associates, Friends, Family and group people tags into these categories. If you have done this. 

when viewing how time you spent on activity tag socializing the last 6 months clicking on it will show the break up of Formal vs Informal and Breakup against Business Associates, Friends, Family etc. 

Clicking on these will show you further breakup.

**Comment by gkrishna63** [comment]
Another option that we are considering that is coming from designing the bot interface. 
In the bot interface creating a tag is done by sending a message tag=[one of person, activity, project, place, other].

We could support recategorization by simply allowing you to type tag=[new category]

We are considering backporting some of the bot syntax to the thick client.

What do you think?
