### ISSUE TITLE
Export TagTime log

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#2]
For the demographic that TagTime targets, this feature is probably needed from the very beginning. It may be hard for people to take the plunge with a new system unless they feel fully in control of their data.

**Comment by theproductiveprogrammer** [comment]
Exporting is a good option and I think we should provide it in the next iteration. The format of export should, I think, be in CSV - it's universally understood and easy to open and play with. Does anyone have other suggestions?

**Comment by dreeves** [comment]
CSV would be a good option but also at this stage we should probably have interoperability with the Perl TagTime. So support for this format:

```
1532465998 work projectfoo (some comment in parens) [2018.07.24 13:59:58 TUE]
1532466974 afk eat (with alice)     [2018.07.24 14:16:14 TUE]
1532468344 afk eat                   [2018.07.24 14:39:04 TUE]
1532470730 work projectbar home [2018.07.24 15:18:50 TUE]
```

Note that things in both parentheses () and brackets [] are treated as comments, and tags are space-separated.

**Comment by theproductiveprogrammer** [comment]
@dreeves This is done and checked-in to the latest version. Do try it out.
