### ISSUE TITLE
A way to tag a range of pings with the same tags

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#3]
(In Perl TagTime, this is done by holding down F4 in the Vim-based ping editor.)

**Comment by theproductiveprogrammer** [comment]
This is done by shift-selecting all the pings in the range. Select the first ping, then press Shift and select the last. All intermediate pings will be auto-selected. Tag changes will then apply to all selected pings at the same time.

**Comment by dreeves** [comment]
Ah, brilliant!
