### ISSUE TITLE
Inscrutable pie chart

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#4]
What is the purple part of this pie chart about?

![image](https://user-images.githubusercontent.com/9928/43443387-91b38a02-9455-11e8-94e8-3bc80fa30b76.png)

**Comment by theproductiveprogrammer** [comment]
@dreeves That is not working right now.... The purple is supposed to be left-over time for the rest of the day/week (where we do not yet have ping entries). I thought a "quick view" of how the day/week was going to may be a helpful chart to give a little guidance on what needs to be taken up next.
