### ISSUE TITLE
Signup button seems unclickable

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#5]
turned out this was kind of PEBKAC, but under the bold assumption that I'm not much dumber than typical users...

> i just clicked "sign up" and assumed it would take me somewhere to sign up. it somehow did not occur to me that it wanted email and password filled in. i thought of those as strictly for the login button, with signup being separate. i'm in now!

To make that a proper bug report:

## Steps to Reproduce

1. Launch app to see login/signup page
2. Don't fill in username/password
3. Click the "Sign up" button

## What Happens

Nothing. Clicking the button seems to be a no-op.

## What I Expected

Either for login and signup to be different screens, or at least give an error message.

**Comment by theproductiveprogrammer** [comment]
Done. I will mail you the latest build to try
