### ISSUE TITLE
Email copy tweaks and copy/paste bug

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#6]
> Subject: here is your verification information from Tagtime
> 
> Hello ,
> 
> Thank you for signing up for Tagtime. The next time you attempt to login, you will be asked for a verification key.
> 
> Please copy and paste the string given below in the Verification Key field

Things I noticed about the above email copy:

- [ ] Let's standardize on camelcase "TagTime" (not "Tagtime", and elsewhere in the app it's "Tag Time")
- [ ] Missing name ("Hello ,")
- [ ] As a verb it's "log in" not "login"
- [ ] Not relevant to the email copy but I couldn't paste the key into the field. Command-V just wouldn't do anything. I had to manually type it in. I'm on macOS High Sierra 10.13.5.

**Comment by theproductiveprogrammer** [comment]
1. Agreed
2. Yes. We were capturing name but simplified the interface. Will fix.
3. Ah I see. Thanks.
4. Yeah I have the same problem. It works while developing but as soon as I build a .dmg package paste stops working. Will figure it out and fix it.
