### ISSUE TITLE
First line of exported log has wrong timestamp

### ISSUE THREAD

**Issue by dreeves** [theproductiveprogrammer/tagtime-ui#7]
I answered a few pings and then exported my log and got this:

```
1534210892 bab                                         [2018.08.13 18:41:32 MON]
1534211430 bab b                                       [2018.08.13 18:50:30 MON]
1534212059 b                                           [2018.08.13 19:00:59 MON]
1534212245                                             [2018.08.13 19:04:05 MON]
```

But that first line does not correspond to any TagTime ping. There was one at 18:37:08 and then the one at 18:50:30.

**Comment by theproductiveprogrammer** [comment]
The 18:41 ping is an "entry" ping that shows up when you first launch TagTime. This is so that a new user can start using the interface immediately (which makes it more usable). This ping has a period of "1 second" rather than the normal "45 minutes" but this doesn't show up in the Perl export format.

**Comment by dreeves** [comment]
I see. That's smart. Can we extend the Perl log format to store the ping frequency for each ping?

I propose curly braces with number of seconds, eg:

```
1534210892 foo bar (comment for humans) [2018.08.13 18:41:32 MON] {2700}
```

And then I think that initial ping should be 0 seconds, not 1.

**Comment by theproductiveprogrammer** [comment]
Zero seconds is a neat idea! I like the idea of extending the perl log format as well. Will do.

**Comment by theproductiveprogrammer** [comment]
Done
